name: Create chowdown image for ARM

on:
  push:
    branches: [ publish ]
  pull_request:
    branches: [ publish ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set environment variables
      run: |
        IMG=chowdown
        echo "name=BUILD_VER::1.0.$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
        echo "name=IMAGE::ghcr.io/darrylcauldwell/chowdown" >> $GITHUB_ENV
        echo "name=BUILD_DATE::$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with: 
        registry: ghcr.io
    - name: Build and push the Docker image
      uses: docker/build-push-action@v2
      with:
        labels: |
          org.opencontainers.image.version=${{ env.BUILD_VER }}
          org.opencontainers.image.authors=${{ github.repository_owner }}
          org.opencontainers.image.created=${{ env.BUILD_DATE }}
          org.opencontainers.image.source=https://github.com/darrylcauldwell/chowdown
        tags: |
          chowdown:latest
        push: true
