name: Create chowdown image

on:
  push:
    branches: [ publish ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with: 
        registry: ghcr.io
        
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ghcr.io/darrylcauldwell/chowdown:latest
          ghcr.io/darrylcauldwell/chowdown:1.0

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
    
