name: Create chowdown image

on:
  push:
    branches: [ publish ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ghcr.io
        username: darrylcauldwell
        password: ${{ secrets.GITHUB_TOKEN }}
          
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ghcr.io/darrylcauldwell/chowdown:latest
          ghcr.io/darrylcauldwell/chowdown:1.4

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
    
