name: Build and push image

on:
  push:
    branches:
      - 'publish'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platform: linux/arm64,linux/amd64
          push: true
          tags: |
            ghcr.io/darrylcauldwell/chowdown:1.0
            ghcr.io/darrylcauldwell/chowdown:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
